// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZb-nfiFmpudPFCUjGgd7tDbe_TNcSrA',
    appId: '1:736727282510:web:29bef431214ccf6e12a41f',
    messagingSenderId: '736727282510',
    projectId: 'onlinesatiss-28055',
    authDomain: 'onlinesatiss-28055.firebaseapp.com',
    storageBucket: 'onlinesatiss-28055.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrgIJqCA52f0vyq0VxXGtaNgkUxTdqlQk',
    appId: '1:736727282510:android:f07cc4c24a76466b12a41f',
    messagingSenderId: '736727282510',
    projectId: 'onlinesatiss-28055',
    storageBucket: 'onlinesatiss-28055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1JY9Nl899lC0TCuVqXruNbiZEpQCOWs',
    appId: '1:736727282510:ios:88e2ac621e9721de12a41f',
    messagingSenderId: '736727282510',
    projectId: 'onlinesatiss-28055',
    storageBucket: 'onlinesatiss-28055.appspot.com',
    iosBundleId: 'com.example.onlineSatis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1JY9Nl899lC0TCuVqXruNbiZEpQCOWs',
    appId: '1:736727282510:ios:88e2ac621e9721de12a41f',
    messagingSenderId: '736727282510',
    projectId: 'onlinesatiss-28055',
    storageBucket: 'onlinesatiss-28055.appspot.com',
    iosBundleId: 'com.example.onlineSatis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgZb-nfiFmpudPFCUjGgd7tDbe_TNcSrA',
    appId: '1:736727282510:web:bca52273353f409e12a41f',
    messagingSenderId: '736727282510',
    projectId: 'onlinesatiss-28055',
    authDomain: 'onlinesatiss-28055.firebaseapp.com',
    storageBucket: 'onlinesatiss-28055.appspot.com',
  );
}
